LsgServer/GMS/Solutions/Gms.Web.Mvc/Controllers/SysLogController.cs
using System.Linq;
using Gms.Domain;
using SharpArch.NHibernate.Web.Mvc;

namespace Gms.Web.Mvc.Controllers
{
    using System.Web.Mvc;
    [HandleError]
    [Authorize]
    public class SysLogController : BaseController
    {
        public ActionResult Index()
        {          
            return View();
        }

        public ActionResult List(SysLogQuery query)
        {
            var list = this.SysLogRepository.GetList(query);
            var data = list.Data.Select(c => SysLogModel.From(c)).ToList();
            var result = new { total = list.RecordCount, rows = data };
            return Json(result);
        }

       
    }

    public class SysLogModel
    {
        public SysLogModel(SysLog log)
        {
            this.LogInfo = log.LogInfo;
            this.User = log.Manager != null ? log.Manager.LoginName : "";
            this.CreateTime = log.CreateTime.ToString("yyyy-MM-dd HH:mm:ss");
        }

        /// <summary>
        /// 日志内容
        /// </summary>
        public string LogInfo { get; set; }

        /// <summary>
        /// 操作用户
        /// </summary>
        public string User { get; set; }

        /// <summary>
        /// 时间
        /// </summary>
        public string CreateTime { get; set; }
        
        public static SysLogModel From(SysLog log)
        {
            return new SysLogModel(log);
        }
    }
}

LsgServer/GMS/Solutions/Gms.Web.Mvc/Views/SysLog/Index.cshtml
@using Gms.Domain

@{
    Layout = "~/Views/Shared/EmptyLayout.cshtml";
}

<body>

    <div id="toolbar" style="padding: 5px; height: auto">
        <div>
            工号：<input name="LoginName" class="messager-input" style="width: 80px" />
            内容：<input name="LogInfo" class="messager-input" style="width: 80px" />
            日期：<input name="CreateTime.Start" class="easyui-datebox" style="width: 80px" />至<input name="CreateTime.End" class="easyui-datebox" style="width: 80px" />
            <a href="#" id="syslog_search" class="easyui-linkbutton search" iconcls="icon-search">搜索</a>
        </div>
    </div>
     
    <table id="syslog_search_list" url="@Url.Action("List","SysLog")">
            
    </table>
        
</body>
<script type="text/javascript" src="@Url.Content("/Scripts/SysLog/SysLog.js")"></script>
<script type="text/javascript">
    $(document).ready(function () {
        SysLog.Init();
    });
</script>